//! The recall gate: OCR the committed fixtures and check that the text we care
//! about came back.
//!
//! This is an example rather than a test because it needs a loadable
//! `libtesseract` with `eng`+`hrv` tessdata, and `cargo test` has to stay green
//! on a machine that has neither. `just recall` runs it; run it after anything
//! that touches `ocr.rs`, `tess.rs`, or the OCR defaults in `config.rs`.
//!
//! ```text
//! cargo run --release --example recall -- [fixtures_dir]   # check
//! cargo run --release --example recall -- [fixtures_dir] --dump   # show text
//! ```
//!
//! The fixtures are generated by `scripts/make_fixtures.py`; the strings below
//! are also listed in `tests/fixtures/README.md`.
//!
//! **Substrings, not transcripts.** Each fixture asserts a handful of phrases
//! that must appear in the recovered text, not the whole output. A rotated page
//! or a low-contrast scan will drop a comma, split a word, or reorder columns
//! depending on the Tesseract build and version, and a gate that fails on that
//! is a gate people learn to ignore. The phrases are chosen so that a real
//! regression — a language pack that stopped loading, a confidence floor that
//! started eating body text, a segmentation mode that lost a whole column —
//! cannot pass.

use std::path::PathBuf;

use lensquery::ocr::{self, Ocr};
use lensquery::tess;

/// (filename, phrases that must appear in the recovered text).
const FIXTURES: [(&str, &[&str]); 7] = [
    // The sanity case: if this fails nothing else is worth reading.
    ("hello_world.png", &["Hello World"]),
    // Diacritics survive rendering, OCR, and UTF-8 handling. One word per
    // accented letter rather than a `čćžšđ` cluster: Tesseract scores against a
    // language model, so a nonsense run of accents lands under the confidence
    // floor and drops out for reasons unrelated to diacritic handling. `đ` is
    // the one that historically broke.
    (
        "croatian_text.png",
        &[
            "Dobar dan",
            "izvještaja",
            "Čaša",
            "žuto",
            "ćevapi",
            "đak",
            "šuma",
        ],
    ),
    // Structure: a heading, a body line, and the numbers — the total in
    // particular, since a document you cannot recover the total from is a
    // document you cannot search for.
    (
        "invoice.png",
        &[
            "INVOICE",
            "Northwind Analytics",
            "Optical character",
            "1629.50",
        ],
    ),
    // Light-on-dark UI chrome at UI sizes, including a monospaced field.
    (
        "ui_panel.png",
        &[
            "Deployment Settings",
            "europe-west3",
            "cargo build",
            "Save changes",
        ],
    ),
    // Faded grey on grainy paper. This is the fixture that notices if the
    // confidence floor starts dropping legitimate words.
    (
        "low_contrast_scan.png",
        &["archive", "eleven years", "44-119-B"],
    ),
    // Four degrees off square. Tesseract deskews; this proves it still does.
    (
        "rotated_page.png",
        &["Meeting notes", "migration is scheduled", "platform team"],
    ),
    // Both columns must come back. Order is not asserted — see the header.
    (
        "two_column.png",
        &[
            "Quarterly Field Report",
            "reservoirs recovered",
            "boreholes were drilled",
        ],
    ),
];

fn main() {
    tess::init_process_env();

    let mut args = std::env::args().skip(1);
    let mut dir: Option<PathBuf> = None;
    let mut dump = false;
    for arg in args.by_ref() {
        if arg == "--dump" {
            dump = true;
        } else {
            dir = Some(PathBuf::from(arg));
        }
    }
    let dir = dir.unwrap_or_else(|| PathBuf::from("tests/fixtures"));

    if !tess::available() {
        eprintln!("libtesseract not loadable — cannot run the recall gate.");
        eprintln!("run `lq doctor` to see every path that was tried.");
        std::process::exit(2);
    }
    println!("libtesseract: {:?}\n", tess::library_path());

    let mut failures = 0;
    for (name, phrases) in FIXTURES {
        let path = dir.join(name);
        let got = ocr::extract_text(
            &path,
            "eng+hrv",
            40.0,
            false,
            ocr::DEFAULT_THOROUGH_TRIGGER_WORDS,
        );
        let text = match &got {
            Ocr::Text(t) => t.as_str(),
            Ocr::Empty => "",
            Ocr::Failed => {
                println!("[FAIL] {name}: OCR failed outright");
                failures += 1;
                continue;
            }
        };

        if dump {
            println!("--- {name} ---\n{text}\n");
        }

        let missing: Vec<&str> = phrases
            .iter()
            .copied()
            .filter(|p| !text.contains(p))
            .collect();
        if missing.is_empty() {
            println!("[PASS] {name}: {} phrase(s)", phrases.len());
        } else {
            failures += 1;
            println!("[FAIL] {name}: missing {missing:?}");
            if !dump {
                println!("       got: {text:?}");
            }
        }
    }

    // Tear the engine down while the library is still live, to avoid
    // Tesseract's ObjectCache "LEAK" warnings on process exit.
    tess::shutdown();

    if failures == 0 {
        println!("\nRECALL GATE: PASS ({} fixtures)", FIXTURES.len());
    } else {
        eprintln!("\nRECALL GATE: FAIL ({failures} fixture(s) drifted)");
        std::process::exit(1);
    }
}
